# Generated by Django 4.2.7 on 2023-12-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("marks", models.CharField(max_length=100)),
                ("per", models.CharField(max_length=100)),
            ],
        ),
    ]
